language: node_js

node_js:
  - "stable"
  - "6"
  - "5"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5

script: npm run ci

addons:
  code_climate:
    repo_token: 4155f5c34bf061ab95c85ee7badd212515aa39bb52461f2d7ead67dd72864a59
