development:
  adapter: postgresql
  encoding: unicode
  database: eggcount_development
  pool: 5
  username: eggcount
  password:

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: eggcount_production
  pool: 5
  username: eggcount
  password:
