development:
  adapter: postgresql
  encoding: unicode
  database: eggcount_development
  pool: 5
  username: eggcount
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: eggcount_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: eggcount_production
  pool: 5
  username: eggcount
  password:
